# Generated by Django 4.0.3 on 2022-07-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_computer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceid',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
