# Generated by Django 4.0.3 on 2022-07-03 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_deviceid_id_alter_scanresult_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='scanresult_computer_id',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.computer'),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='scanresult_deviceid_id',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.deviceid'),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='scanresult_subnet_id',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.subnet'),
        ),
    ]
