# Generated by Django 4.0.5 on 2022-08-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceid',
            name='deviceid_note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
    ]
